name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true                
        default: 'World'                
      message:
        description: 'Message to display'
        required: false
        default: 'Hello'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Manual Trigger Test
      run: |
        echo "${{ github.event.inputs.message }} ${{ github.event.inputs.name }}!"